#
# setup mysql with MariaDB
#
- name: check password complexity
  fail:
    msg: You're using the default password, please change it or override it in your own playbook!
  when: mysql_root_password == "my!mySQLpassw0rd@"
  tags: debug

- name: uninstall mariadb-libs (postfix dep) for compatibility workaround
  yum:
    name: mariadb-libs
    state: absent
  tags:
    - mysql

- name: install mariadb
  yum:
    name: "{{ mysql_packages }}"
    state: present
  notify:
    - restart mysql
  tags:
    - mysql

- name: install mariadb bridges
  yum:
    name: "{{ mysql_bridges }}"
    state: present
  notify:
    - restart mysql
  tags:
    - mysql

- name: enable mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
  tags:
    - mysql

- name: update mariadb root password credentials
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
  tags:
    - mysql

- name: sync .my.cnf file with root password credentials
  template:
    src: .my.cnf
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  tags:
    - mysql

- name: update mariadb root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  tags:
    - mysql

- name: delete anonymous and test mariadb users
  mysql_user:
    name: "{{ item }}"
    state: absent
  with_items:
    - ""
    - test
  tags:
    - mysql

- name: set mariadb parameters
  lineinfile:
    dest: /etc/my.cnf.d/mariadb-server.cnf
    regexp: '^{{ item.param }} *?='
    insertafter: '{{ item.pos|replace("[", "\[")|replace("]", "\]") }}'
    line: "{{ item.param }}={{ item.value }}"
  with_items:
    - { param: 'bind-address', value: '127.0.0.1', pos: '[server]' }
    - { param: 'max_heap_table_size', value: '32M', pos: '[mysqld]' }
    - { param: 'tmp_table_size', value: '32M', pos: '[mysqld]' }
    - { param: 'query_cache_size', value: '128M', pos: '[mysqld]' }
    - { param: 'innodb_buffer_pool_size', value: '384M', pos: '[mysqld]' }
    - { param: 'max_allowed_packet', value: '256M', pos: '[mysqld]' }
  notify:
    - restart mysql
  tags:
    - mysql
    - mysql_config

- name: create mariadb databases
  mysql_db:
    db: "{{ item }}"
    state: present
  with_items: "{{ mysql_databases[inventory_hostname] | default([]) }}"
  tags:
    - mysql
